language: swift
xcode_project: LuCalc.xcodeproj
osx_image: xcode9
xcode_sdk: iphonesimulator11.0
xcode_scheme: LuCalcUITests
script: xcodebuild test -project LuCalc.xcodeproj -scheme LuCalcUITests -destination 'platform=iOS Simulator,name=iPhone X,OS=11.0'
